version: '3.5'

services:
  postgres:
    container_name: my_todo_list_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_todo_list
    ports:
      - "5432:5432"
    restart: always
